use_frameworks!

platform :ios, '13.0'

target 'Cardboard_Example' do

  pod 'Cardboard',      :path => '../'
  pod 'Espresso/UIKit', '~> 2.0'

  pod 'Reveal-SDK',     :configurations => ['Debug']

  target 'Cardboard_Tests' do
    inherit! :search_paths  
  end
  
end
